name: Deploy Application

on:
    push:
        branches:
         - main
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
             - name: Deploy to Render
               if: success()
               run: |
                  curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}